// Generated by https://quicktype.io

export interface PostLogin {
    usuario: Usuario;
    token:   string;
}

export interface Usuario {
    rol:    string;
    estado: boolean;
    google: boolean;
    nombre: string;
    correo: string;
    img:    string;
    uid:    string;
    opciones: [
        {
            _id:string;
            clave: string;
            titulo: string;
            ruta: string;
        }
    ]
}
